# General information
#   https://github.com/thomasloven/hass-config/wiki/Misc-tricks#cardelemententity-row-triality
#   http://thomasloven.com/blog/2018/08/YAML-For-Nonprogrammers/
#   https://github.com/thomasloven/hass-config/wiki
#
# Aufteilung und Wiederholung
#   https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/341
#   https://github.com/thomasloven/lovelace-card-mod/wiki/Card-mod-Themes

title: Home Max&Ing
button_card_templates: !include_dir_merge_named ./lovelace/templates/button-card
background: var(--background-image)

# old: compact-custom-header
#   https://maykar.github.io/compact-custom-header/
# Custom Header (Nachfolger von compact-custom-header)
#   https://maykar.github.io/custom-header/#configuration/main
# deprecated, not maintained anymore
#custom_header: !include lovelace/custom_header.yaml
# replace Functionality with themes/card-mod:
#   https://github.com/thomasloven/lovelace-card-mod/wiki/Theme-cookbook#compactcustom-header

# swipe-navigation
#   https://github.com/maykar/lovelace-swipe-navigation
swipe_nav:
  wrap: false # ende <-> anfang
  animate: swipe  # swipe, fade, flip
  skip_tabs: zha_table
  prevent_default: true
  swipe_amount: 35

views:
  # 1: main view containing presence status and all important/urgent items
  - !include lovelace/views/home_view.yaml

  # 2: show local weather conditions and forecast
  - !include lovelace/views/weather_view.yaml
  
  # 3: view to operate the vacuum cleaner and all related params
  - !include lovelace/views/vacuum_view.yaml

  # 4: view for room climate control
  - !include lovelace/views/climate_view.yaml

  # 5:view to operate TV (doesn't work yet)
  - !include lovelace/views/media_view.yaml

  # 7: view to monitor internet-connection, network, network devices
  - !include lovelace/views/monitoring_view.yaml

  # 8: table with zigbee devices
  - !include lovelace/views/zigbee_view.yaml

  # 6: view for plant sensors and care taking
  - !include lovelace/views/plants_view.yaml

  # 9: HA-Administration
  - title: Wartung
#    visible:
#      - user: 69c..
    icon: mdi:tools
    path: maintenance
    cards:
      - type: entities
        entities:
          - entity: input_select.debug_mode

