# https://github.com/thomasloven/hass-config/wiki/Misc-tricks#cardelemententity-row-triality
# http://thomasloven.com/blog/2018/08/YAML-For-Nonprogrammers/

title: Home Max&Ing
resources:
  # Community Repo
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
    type: js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module    
  - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
    type: js
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/group-card/group-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/zha-network-card/zha-network-card.js
    type: js
  # Repo: https://github.com/sgttrs/lovelace-weather-card-chart
  - url: /community_plugin/lovelace-weather-card-chart/weather-card-chart.js
    type: module

# compact-custom-header
#   https://maykar.github.io/compact-custom-header/
# Custom Header (Nachfolger von compact-custom-header)
#   https://maykar.github.io/custom-header/#configuration/main
custom_header:
  compact_mode: true
  menu_hide: false
  voice_hide: true
  chevrons: false

  tab_icons:
    home: '{% if is_state("input_boolean.open_backdoor_alert", "on") or is_state("input_boolean.open_window_alert", "on") %}mdi:home-alert{% endif %}'
    weather: '{% if is_state("input_boolean.dwd_weather_alert", "on") %}mdi:weather-lightning{% endif %}'
    #auch: mdi:flash-circle
  tabs_color:
    home: '{% if is_state("input_boolean.open_backdoor_alert", "on") %}red{% elif is_state("input_boolean.open_window_alert", "on") %}yellow{% endif %}'
    weather: '{% if states.sensor.dwd_current_warn_count.state|int > 0 %}red{% elif states.sensor.dwd_advance_warn_count.state|int > 0 %}yellow{% endif %}'
  exceptions:
    - conditions:
        user: !secret username_ing
        user_agent: Mobile
      config:
        menu_hide: true
        disabled_mode: false
        show_tabs: "home,weather,vacuum" #,plants,climate"
        hide_help: true
        hide_config: true
        hide_unused: true
    - conditions:
        user: !secret username_max
        user_agent: iPhone
      config:
        menu_hide: false
        disabled_mode: false
        show_tabs: "0 to 2, 4, 5, 6"
#        hide_tabs: "plants,climate,zha_table,maintenance"
        hide_help: true
        hide_config: true
        hide_unused: false

# swipe-navigation
#   https://github.com/maykar/lovelace-swipe-navigation
swipe_nav:
  wrap: false # ende <-> anfang
  animate: swipe  # swipe, fade, flip
  skip_tabs: 6, zha_table
  prevent_default: true
  swipe_amount: 35

views:
  # main view containing presence status and all important/urgent items
  - !include lovelace/views/home_view.yaml

  # show local weather conditions and forecast
  - !include lovelace/views/weather_view.yaml
  
  # view to operate the vacuum cleaner and all related params
  - !include lovelace/views/vacuum_view.yaml

  # view for plant sensors and care taking
  - !include lovelace/views/plants_view.yaml

  # view for room climate control
  - !include lovelace/views/climate_view.yaml

  # view to operate TV (doesn't work yet)
#  - !include lovelace/views/media_view.yaml

  # view to monitor internet-connection, network, network devices
  - !include lovelace/views/monitoring_view.yaml

  # table with zigbee devices and network params
  - !include lovelace/views/zigbee_view.yaml

  - title: Wartung
    icon: mdi:tools
    path: maintenance
    cards:
      - type: 'custom:group-card'
        card:
          type: entities
          title: Batterie Status
          show_header_toggle: false
        group: group.battery_status
      - type: 'custom:group-card'
        card:
          type: entities
          title: Batterie Alert
          show_header_toggle: false
        group: group.battery_alert
