###############################################################################
#   @author       : Max Reigl
#   @changed      : 16.10.2024
#   @created:     : 29.04.2022
#   @package      : doors_windows
#   @description  : Notifications of status of open doors and windows
#   @links        : 
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: "doors_windows"
      door: &door
        <<: *common
        device_class: door
      window: &window
        <<: *common
        device_class: window
  # constants
      # delays for notifications 
      int_seconds_alert_send_delay: &int_seconds_alert_send_delay 5 #default: 5
      int_seconds_alert_reset_delay: &int_seconds_alert_reset_delay 1 #default: 1
  # sensors
    binary_sensor.door_g1_offnung:
      friendly_name: Gästezimmer
      <<: *door
    binary_sensor.door_w1_offnung:
      friendly_name: Wohnzimmer W
      battery last changed: 08.06.2024
      <<: *door
    binary_sensor.door_w2_offnung:
      friendly_name: Wohnzimmer S
      battery last changed: 02.02.2024
      <<: *door
    binary_sensor.door_e1_offnung:
      friendly_name: Esszimmer
      battery last changed: 14.12.2023
      <<: *door
    binary_sensor.door_k1_offnung:
      friendly_name: Küche
      <<: *door
    binary_sensor.door_a2_offnung:
      friendly_name: Arbeitszimmer S
      <<: *door
    binary_sensor.door_a1_offnung:
      friendly_name: Arbeitszimmer O
      battery last changed: 11.11.2024
      <<: *door
    binary_sensor.door_s1_offnung:
      friendly_name: Schlafzimmer
      battery last changed: 21.01.2025
      <<: *door
    binary_sensor.door_eingang_offnung:
      friendly_name: Eingang
      <<: *door
    binary_sensor.window_b1_offnung:
      friendly_name: Bad
      battery last changed: 05.06.2023
      <<: *window
    binary_sensor.window_b2_offnung:
      friendly_name: Gästebad
      battery last changed: 18.10.2024
      <<: *window
  # groups, variables
    group.all_doors:
      <<: *common
    group.all_windows:
      <<: *common
    group.entrance_door:
      <<: *common
    input_boolean.open_backdoor_alert:
      <<: *common
    input_boolean.open_window_alert:
      <<: *common
    input_boolean.ll_signals_doorstatus:
      <<: *common
    input_boolean.disable_signal_automation:
      <<: *common
    input_boolean.show_signal:
      <<: *common
    switch.enable_signal_automation:
      <<: *common
    switch.show_signal:
      <<: *common
  # automations
    automation.LL_signal_status:
      <<: *common
    automation.LL_status_signal_off:
      <<: *common
    automation.notify_all_open_doors:
      <<: *common
    automation.notify_all_open_windows:
      <<: *common
    automation.reset_alert_open_doors:
      <<: *common
    automation.reset_alert_open_windows:
      <<: *common
    automation.test_zone_notify:
      <<: *common

###############################################################################
##  Groups
###############################################################################
group:
  # 'group.all_doors' fasst den Status aller Türen zusammen.
  #   Ist ein Türsensor 'on'='Offen', dann wird die Gruppe 'on'.
  all_doors:
    name: alle Türen
    icon: mdi:door
    entities:
      - binary_sensor.door_g1_offnung #1 Gästezimmer
      - binary_sensor.door_w1_offnung #2 Wohnzimmer W
      - binary_sensor.door_w2_offnung #3 Wohnzimmer S
      - binary_sensor.door_e1_offnung #4 Esszimmer
      - binary_sensor.door_k1_offnung #5 Küche
      - binary_sensor.door_a2_offnung #6 Büro S
      - binary_sensor.door_a1_offnung #7 Büro O
      - binary_sensor.door_s1_offnung #8 Schlafzimmer
  all_windows:
    name: alle Fenster
    icon: mdi:window-closed
    entities:
      - binary_sensor.window_b1_offnung #12: Bad
      - binary_sensor.window_b2_offnung #13: Gästebad
      #fehlt: SZ, Dachfenster
  entrance_door:
    name: Eingangstür
    icon: mdi:door
    entities:
      - binary_sensor.door_eingang_offnung #9 Eingangstür

###############################################################################
##  Variables
###############################################################################
# value to remember, if an alert is active
input_boolean:
  open_backdoor_alert:
    name: Terrassentür ist offen   #active warning: door is open
    icon: mdi:alert-box-outline
  open_window_alert:
    name: Fenster ist offen   #active warning: window is open
    icon: mdi:alert-box-outline
  #open_frontdoor_alert: to be implemented
  ll_signals_doorstatus:
    name: Türstatus wird angezeigt
    icon: mdi:traffic-light
  #activate/disactivate the automation for doorstatus signal light
  disable_signal_automation:
    name: Ampelschaltung deaktivieren
    icon: mdi:robot
  #show the doorstatus signal light now
  show_signal:
    name: Ampel anzeigen
    icon: mdi:traffic-light-outline

switch:
  - platform: template
    switches: ## are needed in addition to input_booleans to get a dynamic icon
      enable_signal_automation:
        friendly_name: Automatische Ampel #   
        value_template: "{% if not states('input_boolean.disable_signal_automation')=='unknown' %}{{ is_state('input_boolean.disable_signal_automation', 'off') }}{% endif %}"
        turn_on:
          action: homeassistant.turn_off
          data:
            entity_id: input_boolean.disable_signal_automation
        turn_off:
          action: homeassistant.turn_on
          data:
            entity_id: input_boolean.disable_signal_automation
        icon_template: >-
          {% if is_state('input_boolean.disable_signal_automation', 'on') %}
            mdi:ghost-off-outline
          {% else %}
            mdi:ghost
          {% endif %}
      show_signal:
        friendly_name: Ampel anzeigen   
        value_template: "{% if not states('input_boolean.show_signal')=='unknown' %}{{ is_state('input_boolean.show_signal', 'on') }}{% endif %}"
        turn_on:
          action: homeassistant.turn_on
          data:
            entity_id: input_boolean.show_signal
        turn_off:
          action: homeassistant.turn_off
          data:
            entity_id: input_boolean.show_signal
        icon_template: >-
          {% if is_state('input_boolean.show_signal', 'on') %}
            mdi:alarm-light-outline
          {% else %}
            mdi:alarm-light-off-outline
          {% endif %}

###############################################################################
##  Scripts
###############################################################################
script:
  flash_light:
    mode: restart
    fields:
      light_id:
        description: 'ID of the light entity to be flashed.'
        example: 'light.<id> (without light domain)'
      count:
        description: 'number of flashes'
        example: '8 (should be int)'
    sequence:
      - action: light.turn_on
        target:
          entity_id: "light.{{ light_id }}"
      - alias: "Cycle light 'count' times"
        repeat:
          count: "{{ count|int * 2 - 1 }}"
          sequence:
            - delay: 2
            - action: light.toggle
              target:
                entity_id: "light.{{ light_id }}"

###############################################################################
##  Automations
###############################################################################
automation:
  #----------------------------------------------------------------------------------
  # Ampelschaltung mit der Lichtleiste Küche
  # Lightstrip kitchen - signals open door/window status
  - id: show_doorstatus_signal_light
    alias: Lichtband zeigt Status
    mode: single #Do not start a new run, if already running.
    #mode: restart #Start a new run, after stopping the previous run.
    triggers: 
      #wenn Eingangstür geöffnet wird oder sich der Status von Türen/Fenstern ändert.
      - trigger: state
        entity_id: group.entrance_door 
        to: 'on' #=open
      - trigger: state
        entity_id: 
          - group.all_doors
          - group.all_windows
      #Automatisierung wird angeschaltet
      - trigger: state
        entity_id: input_boolean.disable_signal_automation
        to: 'off'
      #Statusampel soll dauerhaft angezeigt werden (z.B. zum Debuggen)
      - trigger: state
        entity_id: input_boolean.show_signal
        to: 'on'
    conditions:
      # 'signal_automation' aktiv UND Home status 'Home' UND (Eingangtür offen ODER Ampel dauerhaft anzeigen)
      - and:
        - condition: state
          entity_id: input_boolean.disable_signal_automation
          state: 'off'
        - condition: state
          entity_id: sensor.home_status
          state: 'Home'
        - or:
          - condition: state
            entity_id: group.entrance_door
            state: 'on'
          - condition: state
            entity_id: input_boolean.show_signal
            state: 'on'
    actions:
      # merken, dass wir die Ampel eingeschaltet haben
      - action: input_boolean.turn_on
        entity_id: input_boolean.ll_signals_doorstatus
      - action: python_script.light_store
        data:
          store_name: dw_signal_store
          entity_id:
            - light.philips_lightstrip_ku
          overwrite: false
          all_attribs: true  #saves last color and brightness, even if state='off'. turn light on shortly
      # Welcher Status der Türen/Fenster?
      - choose:
        - conditions: # Mindestens eine Tür ist offen...
          - condition: state
            entity_id: group.all_doors
            state: 'on'
          sequence:
            action: light.turn_on
            data:
              entity_id: light.philips_lightstrip_ku
              brightness: 255
              rgb_color:  [255, 0, 0] #rot
              transition: 0.2
        - conditions: #...sonst wenn mindestens ein Fenster offen ...
          - condition: state
            entity_id: group.all_windows
            state: 'on'
          sequence:
            action: light.turn_on
            data:
              entity_id: light.philips_lightstrip_ku
              brightness: 255
              rgb_color:  [255, 255, 0] #gelb
              transition: 0.2
        default: # ...Türen und Fenster sind zu.
          action: light.turn_on
          data:
            entity_id: light.philips_lightstrip_ku
            brightness: 255
            rgb_color:  [0, 255, 0] #grün
            transition: 0.2

  - id: clear_doorstatus_signal_light
    alias: Lichtband Status löschen
    mode: single #Do not start a new run, if running already. 
    triggers: 
      #Eingangstür wird geschlossen
      - trigger: state
        entity_id: group.entrance_door 
        to: 'off' #=closed
      #Statusampel soll nicht mehr dauerhaft angezeigt werden
      - trigger: state
        entity_id: input_boolean.show_signal
        to: 'off'
    conditions:
      # 'signal_automation' aktiv UND Ampel-Merker an UND Eingangtür zu UND Ampel nicht dauerhaft anzeigen
      - and:
        #Ampel aus, auch wenn Automatisierungen in der zwischenzeit deaktiviert wurden
      #  - condition: state
      #    entity_id: input_boolean.disable_signal_automation
      #    state: 'off'
        - condition: state
          entity_id: input_boolean.ll_signals_doorstatus
          state: 'on'
        - condition: state
          entity_id: group.entrance_door
          state: 'off'
        - condition: state
          entity_id: input_boolean.show_signal
          state: 'off'
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.ll_signals_doorstatus
      - wait_template: "{{ not states('dw_signal_store.light_philips_lightstrip_ku') == 'unknown' }}"
        timeout: '00:00:03'
      - choose:
        - conditions: "{{ wait.completed }}" #wait condition was met = entity exists
          sequence:
            - action: python_script.light_store
              data:
                store_name: dw_signal_store
                operation: restore
                all_attribs: true  #restores old color and brightness, even if state='off'
        default: #wait condition not met = entity does not exist
          - action: light.turn_off #just turn off light
            entity_id: light.philips_lightstrip_ku
            
  #----------------------------------------------------------------------------------
  # Benachrichtigungen & Alarm
  # Notifications and alarm
  - alias: Notify all - Open Doors
    id: send_notification_open_doors
    triggers:
      # niemand zuhause und mindestens eine Tür offen 
      trigger: template
      value_template: >
        {{ states('sensor.home_status') in ['Away', 'Extended Away']  
           and is_state('group.all_doors', 'on') }}
      for:
        seconds: *int_seconds_alert_send_delay
    variables:
      notification_service: >
        {{ 'notify.family_main_devices' if is_state('sensor.ing_status', 'Just Left') else 'notify.max' }}
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.open_backdoor_alert
      - action: "{{ notification_service }}"
        data:
          title: "Smart Home Alarm"
          message: >
            {{states|selectattr('entity_id','in',state_attr('group.all_doors','entity_id'))|selectattr('state','eq','on')|list|count}} {{'Terassentür ist' if states|selectattr('entity_id','in',state_attr('group.all_doors','entity_id'))|selectattr('state','eq','on')|list|count==1 else 'Terassentüren sind'}} offen (und {{states|selectattr('entity_id','in',state_attr('group.all_windows','entity_id'))|selectattr('state','eq','on')|list|count}} Fenster).
          data:
            subtitle: "Türen offen!"
            push:
              badge: "{{states('sensor.count_notification_alerts')|int(default=0)}}"
              sound:
                name: default 
                #name: "US-EN-Daisy-Back-Door-Open.wav" 
                critical: 1
                volume: 1.0
              thread-id: "doorswindows-notification-group"
            apns_headers:
              'apns-collapse-id': 'open-doors-detected'
            clickAction: '/lovelace/home'
  - alias: Notify all - Open Windows
    id: send_notification_open_windows
    triggers:
      # niemand zuhause und mindestens ein Fenster offen (und keine Tür offen)
      trigger: template
      value_template: >
        {{ states('sensor.home_status') in ['Away', 'Extended Away']  
           and is_state('group.all_windows', 'on') 
           and is_state('group.all_doors', 'off') }}
      for:
        seconds: *int_seconds_alert_send_delay
    variables:
      notification_service: >
        {{ 'notify.family_main_devices' if is_state('sensor.ing_status', 'Just Left') else 'notify.max' }}
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.open_window_alert
      - action: "{{ notification_service }}"
        data:
          title: "Smart Home Alarm"
          message: >
            {{states|selectattr('entity_id','in',state_attr('group.all_windows','entity_id'))|selectattr('state','eq','on')|list|count}} Fenster {{'ist' if states|selectattr('entity_id','in',state_attr('group.all_windows','entity_id'))|selectattr('state','eq','on')|list|count==1 else 'sind'}} offen.
          data:
            subtitle: "Fenster offen!"
            push:
              badge: "{{states('sensor.count_notification_alerts')|int(default=0)}}"
              sound:
                name: default
                #name: "US-EN-Daisy-Front-Window-Open.wav"
                critical: 1
                volume: 1.0
              thread-id: "doorswindows-notification-group"
            apns_headers:
              'apns-collapse-id': 'open-windows-detected'
            clickAction: '/lovelace/home'
  
  - alias: Reset alert - Open Doors
    id: reset_notification_open_doors
    triggers:
      # jemand zuhause oder alle Türen zu 
      trigger: template
      value_template: >
        {{ (is_state('sensor.home_status', 'Home')  
              or is_state('group.all_doors', 'off'))
            and is_state('input_boolean.open_backdoor_alert', 'on') }}
      for:
        seconds: *int_seconds_alert_reset_delay
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.open_backdoor_alert
      - action: notify.family_main_devices
        data:
          title: "Smart Home ..."
          message: "Türen Alarm aufgehoben."
          data:
            push:
              badge: "{{states('sensor.count_notification_alerts')|int(default=0)}}"
              thread-id: "doorswindows-notification-group"
            apns_headers:
              'apns-collapse-id': 'open-doors-detected'
            clickAction: '/lovelace/home'
  - alias: Reset alert - Open Windows
    id: reset_notification_open_windows
    triggers:
      # jemand zuhause oder alle Fenster zu 
      trigger: template
      value_template: >
        {{ (is_state('sensor.home_status', 'Home') 
              or is_state('group.all_windows', 'off'))
            and is_state('input_boolean.open_window_alert', 'on') }}
      for:
        seconds: *int_seconds_alert_reset_delay
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.open_window_alert
      - action: notify.family_main_devices
        data:
          title: "Smart Home ..."
          message: "Fenster Alarm aufgehoben."
          data:
            push:
              badge: "{{states('sensor.count_notification_alerts')|int(default=0)}}"
              thread-id: "doorswindows-notification-group"
            apns_headers:
              'apns-collapse-id': 'open-windows-detected'
            clickAction: '/lovelace/home'

#----------------------------------------------------------------------------------
#----------------------------------------------------------------------------------
#Test
  - alias: Test Zone Notify
    id: send_notification_zone_test
    triggers:
      - trigger: zone
        entity_id: person.max #group.phone_max
        zone: zone.tik #zone.home
        event: "leave" # Event is either enter or leave
      - trigger: zone
        entity_id: person.max #group.phone_max
        zone: zone.tik
        event: "enter" # Event is either enter or leave
    conditions:
      - and:
        - or:
          - condition: state
            entity_id: group.all_doors
            state: 'on'
          - condition: state
            entity_id: group.all_windows
            state: 'on'
        - "{{ states('sensor.ing_status') not in ['home', 'Just Arrived'] }}"
    actions:
      - action: notify.max
        data:
          title: "Smart Home Alerts (Zone-test)"
          message: "Mindestens eine Balkontür/Fenster ist offen."
          data:
            subtitle: "Türen/Fenster offen!"
            push:
              badge: "{{states('sensor.count_notification_alerts')|int(default=0)}}"