###############################################################################
#   @author       : Max Reigl
#   @date         : 12.11.2019
#   @package      : fritzbox
#   @description  : Monitoring of FritzBox router and Fritz smart home components
#   @links        : https://git.truenoobs.de/darthsandmann/homeassistant/src/branch/master/disabled/packages/fritzbox.yaml
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: "fritzbox"
  # sensors
    sensor.fritzbox_uptime:
      <<: *common
    sensor.fritz_rate_up:
      <<: *common
    sensor.fritz_rate_down:
      <<: *common
    sensor.fritz_rate_up_max:
      <<: *common
    sensor.fritz_rate_down_max:
      <<: *common
        
################################################
##   Platforms
################################################
## Fritzbox Smart Home (now Config > Integrations)
#fritzbox:
#  devices:
#    - host: !secret fritz_host
#      username: !secret fritz_home_username
#      password: !secret fritz_home_password 

## Fritzbox Network Monitoring (now Config > Integrations)
# this option must be activated in FritzBox
#   Heimnetz > Netzwerk > Netzwerkeinstellungen > Heimnetzfreigaben
#     > Statusinformationen über UPnP übertragen
#sensor:
#  - platform: fritzbox_netmonitor
#    host: !secret fritz_host_ip
#    name: fritzbox


###############################################################################
##  Sensors
###############################################################################
sensor:
  - platform: template
    sensors:
      fritzbox_uptime:
        friendly_name: "Uptime"
        value_template: "{{ ( (as_timestamp(now())|int(default=0) - as_timestamp(states('sensor.fritz_box_6490_cable_device_uptime'))|int(default=0)) / (60*60*24)) | round(0) }}"
        unit_of_measurement: "days"
        icon_template: mdi:restart
      fritz_rate_up: #Current upstream speed in Kbytes/s
        friendly_name: "Upload"
        value_template: "{{ (states('sensor.fritz_box_6490_cable_kb_s_sent')|int(default=0) / 1024 * 8)|round(1) }}"
        icon_template: mdi:cloud-upload
        unit_of_measurement: "MBit/s"
      fritz_rate_down: #Current downstream speed in Kbytes/s
        friendly_name: "Download"
        value_template: "{{ (states('sensor.fritz_box_6490_cable_kb_s_received')|int(default=0) / 1024 * 8)|round(1) }}"
        icon_template: mdi:cloud-download
        unit_of_measurement: "MBit/s"
      fritz_rate_up_max: #Maximum upstream-rate in bytes/s
        friendly_name: "Upload Max"
        value_template: "{{ (states('sensor.fritz_box_6490_cable_max_kbit_s_sent')|int(default=0) / 1024)|round(1) }}"
        icon_template: mdi:transfer-up
        unit_of_measurement: "MB/sec"
      fritz_rate_down_max: #Maximum downstream-rate in bytes/s
        friendly_name: "Download Max"
        value_template: "{{ (states('sensor.fritz_box_6490_cable_max_kbit_s_received')|int(default=0) / 1024)|round(1) }}"
        icon_template: mdi:transfer-down
        unit_of_measurement: "MB/sec"

###############################################################################
##  Scripts
###############################################################################
script:
  fritzbox_reconnect:
    alias: "Reconnect Fritz!Box"
    sequence:
      - service: fritz.reconnect
        data:
          device_id: !secret fritzbox_device_id

  fritzbox_reboot:
    alias: "Reboot Fritz!Box"
    sequence:
      - service: fritz.reboot
        data:
          device_id: !secret fritzbox_device_id