###############################################################################
#   @author       : Max Reigl
#   @date         : 08.01.2021
#   @package      : lights
#   @description  : light control
#   @links        : 
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: 'lights'
  # constants 
      # entity-id's
      wallswitch_sz_id: &wallswitch_sz_id 0019DBE9943030
      colorlight_ku_entityid: &colorlight_ku_entityid light.philips_lightstrip_ku
      ambientelight_wz_entityid: &ambientelight_wz_entityid light.0008da499c8dbd
  # entities
    light.0008da499c8dbd:
      icon: mdi:ceiling-light
    light.philips_lightstrip_ku:
      icon: mdi:led-strip-variant
  # groups, variables
    input_boolean.disable_light_automation:
      <<: *common
    switch.enable_light_automation:
      <<: *common
  # automations
    automation.random_lights_during_vacation:
      <<: *common
    automation.switch_off_lights:
      <<: *common
    automation.switch_on_lights:
      <<: *common
    automation.switch_off_lights_from_sz:
      <<: *common
    automation.switch_on_lights_from_sz:
      <<: *common
    automation.switch_off_ambientlight_from_sz:
      <<: *common
    automation.switch_on_ambientlight_from_sz:
      <<: *common
          
################################################
##   Platforms
################################################
scene:
  - name: Welcome
    icon: 'mdi:flower-tulip'
    entities:
      light.0008da499c8dbd:
        state: 'on'
        #brightness: 250 #-->.brightness=249
        brightness: 125 #-->.brightness=
  - name: Movies
    entities:
      light.0008da499c8dbd:
        state: 'on'
        #brightness: 125 #-->.brightness=124
        brightness: 75 #-->.brightness=30%


###############################################################################
#                               Variables
###############################################################################
input_boolean:
  disable_light_automation:
    name: Lichtschaltung deaktivieren
    icon: mdi:robot

switch:
  - platform: template
    switches: ## are needed in addition to input_booleans to get a dynamic icon
      enable_light_automation:
        friendly_name: Automatische Lichtschaltung #   
        value_template: "{% if not states('input_boolean.disable_light_automation')=='unknown' %}{{ is_state('input_boolean.disable_light_automation', 'off') }}{% endif %}"
        turn_on:
          service: homeassistant.turn_off
          data:
            entity_id: input_boolean.disable_light_automation
        turn_off:
          service: homeassistant.turn_on
          data:
            entity_id: input_boolean.disable_light_automation
        icon_template: >-
          {% if is_state('input_boolean.disable_light_automation', 'on') %}
            mdi:ghost-off 
          {% else %}
            mdi:ghost
          {% endif %}


###############################################################################
#                               Automations
###############################################################################
automation:
  #----------------------------------------------------------------------------------
  # Urlaubslicht
  # https://community.home-assistant.io/t/new-automation-not-loading-random-switching-of-lights-when-away-on-holiday/211414/14
  - id: random_lights_during_vacation
    alias: zufälliges Urlaubslicht
    trigger:
      - platform: sun
        event: sunset
      - platform: time
        at: '23:00:00'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.disable_light_automation
        state: 'off'
      - condition: state
        entity_id: sensor.home_status
        state: 'Extended Away'
    action:
      - delay:
          minutes: "{{ range(5, 25 if trigger.platform == 'sun' else 90) | random }}"
      - service: "light.turn_{{ 'on' if trigger.platform == 'sun' else 'off' }}"
        entity_id: *ambientelight_wz_entityid
#  or with groups like that: 
#      - service: "homeassistant.turn_{{ 'on' if trigger.platform == 'sun' else 'off' }}"
#        entity_id: group.holiday_lights
    
  #----------------------------------------------------------------------------------
  # Welcome-/Ambientelicht 
  # Einschalten von Welcome-Licht, wenn wir nach Hause kommen ODER bei Sonnenuntergang
  - id: switch_on_lights
    alias: switch on welcome light
    trigger:
      - platform: state
        entity_id: sensor.home_status
        to: 'Home'
      - platform: sun
        event: sunset
        offset: '+00:15:00' # Optional time offset. 
      - platform: state
        entity_id: input_boolean.disable_light_automation
        to: 'off'
    condition:
      # 'light_automation' aktiv UND Home status 'Home' UND Sonne untergegangen
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.disable_light_automation
        state: 'off'
      - condition: state
        entity_id: sensor.home_status
        state: 'Home'
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
      # und nicht nach systemstart
      # todo
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.welcome
          transition: 2 #[sec] langsamer Übergang
  
  # Ausschalten von Welcome-Licht und Lichtleiste, wenn wir für 10min weg sind oder nachts um 00:00
  #   und morgens beim Sonnenaufgang
  - id: switch_off_lights
    alias: switch off welcome light
    trigger: 
      - platform: state
        entity_id: sensor.home_status
        from: 'Home'
        to: 'Away'
        for:
          minutes: 2
      - platform: state
        entity_id: input_boolean.disable_light_automation
        to: 'off'
      - platform: time 
        at: '00:01:00'
      - platform: sun
        event: sunrise
      - platform: homeassistant
        event: start      
    condition:
      # 'light_automation' aktiv UND (Home status away ODER nach 0:00)
      condition: and
      conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: sensor.home_status
          state: 'Away'
        - condition: time
          after: '00:00:00'
          before: '06:00:00'
      - condition: state
        entity_id: input_boolean.disable_light_automation
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: 
          - *ambientelight_wz_entityid
          - *colorlight_ku_entityid
    
  #----------------------------------------------------------------------------------
  # HmIP-BRC2 Wandtaster schaltet Lichter an/aus
  - id: switch_off_ambientlight_from_sz
    alias: 'Ambientelicht aus'
    trigger:
      platform: event
      event_type: homematic.keypress
      event_data:
        name: *wallswitch_sz_id
        channel: 1
        param: PRESS_SHORT
    action:
      service: light.turn_off
      entity_id: *ambientelight_wz_entityid
  - id: switch_off_lights_from_sz
    alias: 'alle Licher aus'
    trigger:
      platform: event
      event_type: homematic.keypress
      event_data:
        name: *wallswitch_sz_id
        channel: 1
        param: PRESS_LONG
    action:
      - service: light.turn_off
        entity_id: *ambientelight_wz_entityid
      - service: light.turn_off
        entity_id: *colorlight_ku_entityid
  
  - id: switch_on_ambientlight_from_sz
    alias: 'Ambientelicht an'
    trigger:
      platform: event
      event_type: homematic.keypress
      event_data:
        name: *wallswitch_sz_id
        channel: 2
        param: PRESS_SHORT
    action:
      service: light.turn_on
      entity_id: *ambientelight_wz_entityid
  - id: switch_on_lights_from_sz
    alias: 'alle Licher an'
    trigger:
      platform: event
      event_type: homematic.keypress
      event_data:
        name: *wallswitch_sz_id
        channel: 2
        param: PRESS_LONG
    action:
      - service: light.turn_on
        entity_id: *ambientelight_wz_entityid
      - service: light.turn_on
        entity_id: *colorlight_ku_entityid