###############################################################################
#   @author       : Max Reigl
#   @changed      : 10.01.2026
#   @created      : 08.01.2021
#   @package      : lights
#   @description  : light control
#   @links        : 
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: 'lights'
  # constants 
      # entity-id's
      wallswitch_sz_id: &wallswitch_sz_id 0019DBE9943030 #lichttaster_sz
      wallswitch_sz_name: &wallswitch_sz_name lichttaster_sz
      colorlight_ku_entityid: &colorlight_ku_entityid light.philips_lightstrip_ku
      ambientelight_wz_entityid: &ambientelight_wz_entityid light.dimmschalter_wz_dimmaktor_wz  #.0008da499c8dbd
      light_az_entityid: &light_az_entityid light.dimmschalter_buro_dimmaktor_buro  #.0008dd899c4781
  # entities
    # light.dimmschalter_wz_dimmaktor_wz:
    #   icon: mdi:ceiling-light-multiple-outline
    # light.dimmschalter_buro_dimmaktor_buro:
    #   icon: mdi:globe-light
    # light.philips_lightstrip_ku:
    #   icon: mdi:led-strip-variant
  # groups, variables
    input_boolean.disable_light_automation:
      <<: *common
    switch.enable_light_automation:
      <<: *common
  # automations
    automation.random_lights_during_vacation:
      <<: *common
    automation.switch_off_lights:
      <<: *common
    automation.switch_on_lights:
      <<: *common
    automation.switch_off_lights_from_sz:
      <<: *common
    automation.switch_on_lights_from_sz:
      <<: *common
    automation.switch_off_ambientlight_from_sz:
      <<: *common
    automation.switch_on_ambientlight_from_sz:
      <<: *common
          
################################################
##   Platforms
################################################
scene:
  - name: Welcome
    icon: 'mdi:flower-tulip'
    entities:
      light.dimmschalter_wz_dimmaktor_wz:
        state: 'on'
        #brightness: 250 #-->.brightness=249
        brightness: 125 #-->.brightness=
  - name: Movies
    entities:
      light.dimmschalter_wz_dimmaktor_wz:
        state: 'on'
        #brightness: 125 #-->.brightness=124
        brightness: 75 #-->.brightness=30%
      # light.dimmschalter_buro_dimmaktor_buro:
      #   state: 'off'
  - name: Office_dark
    entities:
      light.0008dd899c4781:
        state: 'on'
        #brightness: 125 #-->.brightness=124
        brightness: 75 #-->.brightness=10%

###############################################################################
#                               Variables
###############################################################################
input_boolean:
  disable_light_automation:
    name: Lichtschaltung deaktivieren
    icon: mdi:robot

template:
  - switch:
    ## are needed in addition to input_booleans to get a dynamic icon
    - unique_id: enable_light_automation
      default_entity_id: switch.enable_light_automation
      name: Automatische Lichtschaltung
      turn_on:
        - action: homeassistant.turn_off
          data:
            entity_id: input_boolean.disable_light_automation
      turn_off:
        - action: homeassistant.turn_on
          data:
            entity_id: input_boolean.disable_light_automation
      state: "{% if not states('input_boolean.disable_light_automation')=='unknown' %}{{ is_state('input_boolean.disable_light_automation', 'off') }}{% endif %}"
      icon: >-
        {% if is_state('input_boolean.disable_light_automation', 'on') %}
          mdi:ghost-off-outline
        {% else %}
          mdi:ghost
        {% endif %}


###############################################################################
#                               Automations
###############################################################################
automation:
  #----------------------------------------------------------------------------------
  # Urlaubslicht
  # https://community.home-assistant.io/t/new-automation-not-loading-random-switching-of-lights-when-away-on-holiday/211414/14
  - id: random_lights_during_vacation
    alias: zufälliges Urlaubslicht
    description: 'Schaltet abends das Wohnzimmerlicht zufällig an, wenn wir länger weg sind.'
    triggers:
      - id: 'sunset'
        trigger: sun
        event: sunset
      - id: 'bedtime'
        trigger: time
        at: '23:00:00'
    conditions:
      - and:
        - condition: state
          entity_id: input_boolean.disable_light_automation
          state: 'off'
        - condition: state
          entity_id: sensor.home_status
          state: 'Extended Away'
    actions:
      - delay:
          minutes: "{{ range(5, 25 if trigger.platform == 'sun' else 90) | random }}"
      - action: "light.turn_{{ 'on' if trigger.platform == 'sun' else 'off' }}"
        entity_id: *ambientelight_wz_entityid
#  or with groups like that: 
#      - action: "homeassistant.turn_{{ 'on' if trigger.platform == 'sun' else 'off' }}"
#        entity_id: group.holiday_lights
    
  #----------------------------------------------------------------------------------
  # Welcome-/Ambientelicht 
  # Einschalten von Welcome-Licht, wenn wir nach Hause kommen ODER bei Sonnenuntergang
  - id: switch_on_lights
    alias: switch on welcome lights
    description: 'Schaltet abends das Wohnzimmerlicht zufällig an, wenn wir länger weg sind.'
    triggers:
      - id: 'returned_home'
        trigger: state
        entity_id: sensor.home_status
        to: 'Home'
      - id: 'sunset'
        trigger: sun
        event: sunset
        offset: '+00:15:00' # Optional time offset. 
      - id: 'config_changed'
        trigger: state
        entity_id: input_boolean.disable_light_automation
        to: 'off'
    conditions:
      # 'light_automation' aktiv UND Home status 'Home' UND Sonne untergegangen
      - and:
        - condition: state
          entity_id: input_boolean.disable_light_automation
          state: 'off'
        - condition: state
          entity_id: sensor.home_status
          state: 'Home'
        - condition: state  # from sunset until sunrise
          entity_id: sun.sun
          state: 'below_horizon'
      # und nicht nach systemstart
      # todo
    actions:
      - action: scene.turn_on
        data:
          entity_id: scene.welcome
          transition: 2 #[sec] langsamer Übergang
  
  # Ausschalten von Welcome-Licht und Lichtleiste, wenn wir für 10min weg sind oder nachts um 00:00
  #   und morgens beim Sonnenaufgang
  - id: switch_off_lights
    alias: alle Lichter aus
    triggers: 
      - id: 'nobody_home'
        trigger: state
        entity_id: sensor.home_status
        from: 'Home'
        to: 'Away'
        for:
          minutes: 2
      - id: 'bedtime'
        trigger: time 
        at: '00:01:00'
      - id: 'sunrise'
        trigger: sun
        event: sunrise
      - id: 'config_changed'
        trigger: state
        entity_id: input_boolean.disable_light_automation
        to: 'off'
      - id: 'ha_started'
        trigger: homeassistant
        event: start      
    conditions:
      # 'light_automation' aktiv UND (Home status away ODER nach 0:00)
      - and:
        - condition: state
          entity_id: input_boolean.disable_light_automation
          state: 'off'
        - or:
          - condition: state
            entity_id: sensor.home_status
            state: 'Away'
          - condition: time
            after: '00:00:00'
            before: '06:00:00'
    actions:
      - action: light.turn_off
        entity_id: 
          - *ambientelight_wz_entityid
          - *colorlight_ku_entityid
          - *light_az_entityid
    

  #----------------------------------------------------------------------------------
  # Lichtampel Durchreiche 
  # Wird die Lichtleiste durch den Wandschalter wieder eingeschaltet, so leuchtet sie dauerhaft mit weissem Licht.
  # Die Lichtleiste soll nach dem Versorgen mit Strom wieder ausgeschaltet werden.
  - id: switch_off_signal_after_poweron
    alias: Lichtleiste aus nach Stromzufuhr
    triggers: 
      #falls die Leiste nicht erreichbar war (was leider nur nach langen Aus-Phasen passiert)
      - trigger: state
        entity_id: light.philips_lightstrip_ku
        from: 'unavailable'
        to: 'on'
        for:
          seconds: 10
      #wenn schnell wieder eingeschaltet
      - trigger: state
        entity_id: light.philips_lightstrip_ku
        to: 'on'
        for:
          minutes: 1
    conditions:
      - and:
        - condition: state
          entity_id: light.philips_lightstrip_ku
          state: 'on'
        - condition: state
          entity_id: input_boolean.ll_signals_doorstatus
          state: 'off'
        - condition: state
          entity_id: input_boolean.show_signal
          state: 'off'
        # white color when powered on
        - condition: template
          value_template: >
            {{ state_attr('light.philips_lightstrip_ku','hs_color')[0]==28.327 and state_attr('light.philips_lightstrip_ku','hs_color')[1]==64.71}}
    actions:
      - action: light.turn_off #just turn off light
        entity_id: light.philips_lightstrip_ku

  #----------------------------------------------------------------------------------
  # HmIP-BRC2 Wandtaster schaltet Lichter an/aus
  - id: switch_off_ambientlight_from_sz
    alias: 'Ambientelicht aus (von SZ)'
    description: ''
    triggers:
      trigger: device
      domain: homematicip_local
      device_id: 248828199b3f92a327f134b7e831fd1f
      event_type: homematic.keypress
      address: *wallswitch_sz_id
      device_type: HmIP-BRC2
      interface_id: piVCCU-HmIP-RF
      type: press_short
      subtype: 2 #oben
    actions:
      action: light.turn_off
      entity_id: *ambientelight_wz_entityid
  - id: switch_off_lights_from_sz
    alias: 'alle Licher aus (von SZ)'
    description: ''
    triggers:
      trigger: device
      domain: homematicip_local
      device_id: 248828199b3f92a327f134b7e831fd1f
      event_type: homematic.keypress
      address: *wallswitch_sz_id
      device_type: HmIP-BRC2
      interface_id: piVCCU-HmIP-RF
      type: press_long_start
      subtype: 2 #oben
    actions:
      - action: light.turn_off
        entity_id: *ambientelight_wz_entityid
      - action: light.turn_off
        entity_id: *colorlight_ku_entityid
      - action: light.turn_off
        entity_id: *light_az_entityid
  
  - id: switch_on_ambientlight_from_sz
    alias: 'Ambientelicht an (von SZ)'
    description: ''
    triggers:
      trigger: device
      domain: homematicip_local
      device_id: 248828199b3f92a327f134b7e831fd1f
      event_type: homematic.keypress
      address: *wallswitch_sz_id
      device_type: HmIP-BRC2
      interface_id: piVCCU-HmIP-RF
      type: press_short
      subtype: 1 #unten
    actions:
      action: light.turn_on
      entity_id: *ambientelight_wz_entityid
  - id: switch_on_lights_from_sz
    alias: 'Licher an (von SZ)'
    description: ''
    triggers:
      trigger: device
      domain: homematicip_local
      device_id: 248828199b3f92a327f134b7e831fd1f
      event_type: homematic.keypress
      address: *wallswitch_sz_id
      device_type: HmIP-BRC2
      interface_id: piVCCU-HmIP-RF
      type: press_long_start #press', 'press_cont', 'press_long', 'press_long_release', 'press_long_start', 'press_short'
      subtype: 1 #unten
    actions:
      - action: light.turn_on
        entity_id: *ambientelight_wz_entityid
      - action: light.turn_on
        data:
          brightness_pct: 10
        target:
          entity_id: *light_az_entityid
