###############################################################################
#   @author       : Max Reigl
#   @date         : 08.11.2019
#   @package      : network
#   @description  : various sensors for network devices, services and performance
#   @links        : 
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: "network"
  # sensors
    # system monitor
    sensor.memory_free:
      <<: *common
    sensor.disk_use_percent:
      <<: *common
    sensor.processor_use:
      <<: *common
    sensor.network_in_eth0:
      <<: *common
    sensor.network_out_eth0:
      <<: *common
    sensor.last_boot:
      <<: *common
    # HA
    sensor.historydb_size:
      <<: *common
    sensor.current_version:
      <<: *common
    sensor.latest_version:
      <<: *common
    # Speedtest.net Sensors 
    sensor.speedtest_ping:
      <<: *common
      friendly_name: Ping
    sensor.speedtest_upload:
      <<: *common
      friendly_name: Upload Speed
      icon: mdi:cloud-upload
    sensor.speedtest_download:
      <<: *common
      friendly_name: Download Speed
      icon: mdi:cloud-download
    # Raspberries
    sensor.raspi1_cpu_usage:
      <<: *common
      icon: mdi:cpu-64-bit
    sensor.raspi2_cpu_usage:
      <<: *common
      icon: mdi:cpu-64-bit
    binary_sensor.rpi_ost:
      <<: *common
    binary_sensor.rpi_west:
      <<: *common
    binary_sensor.rpi_sued:
      <<: *common
    binary_sensor.devolo_bridge:
      <<: *common
    binary_sensor.devolo_steuerkasten:
      <<: *common
    binary_sensor.devolo_keller:
      <<: *common
    # other devices
    binary_sensor.smarttv:
      <<: *common
      icon: mdi:television  #television-classic-off
    binary_sensor.roborock:
      <<: *common
      icon: mdi:robot-vacuum
    binary_sensor.radiobad:
      <<: *common
      icon: mdi:radio
#    binary_sensor.router:
#      <<: *common
#      icon: mdi:router-network

################################################
##   Platforms
################################################
sensor:
  # raspi1Sensors, raspi2Sensors: 
    # werden automatisch erzeugt (MQTT)
  # monitor Home Assistant system state
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: last_boot
  # monitor Home Assistant database size
#  - platform: sql
#    db_url: !secret HistoryDB_connection
#    queries:
#    - name: historydb_size
#      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 1) "value" FROM information_schema.tables WHERE table_schema="HAhistory" GROUP BY table_schema'
#      column: 'value'
#      unit_of_measurement: MB
  # check on the version of Home Assistant
#  - platform: version
#    source: local
#  - platform: version
#    source: docker


###############################################################################
##  Sensors
###############################################################################
binary_sensor:
  # Monitor IP-connection to systems state
#  - platform: ping
#    host: !secret fritz_host_ip
#    name: router
#    scan_interval: 30
#    count: 2
  - platform: ping
    host: !secret samsung_tv_ip
    name: smarttv
    scan_interval: 300
    count: 2
  - platform: ping
    host: !secret xiaomi_vacuum_ip
    name: roborock
    scan_interval: 120
    count: 2
  - platform: ping
    host: !secret radio_bad_ip
    name: radiobad
    scan_interval: 120
    count: 2
  - platform: ping
    host: raspi1
    name: rpi_ost
    scan_interval: 15
    count: 2
  - platform: ping
    host: raspi2
    name: rpi_west
    scan_interval: 60
    count: 2
  - platform: ping
    host: !secret raspi3_sued_ip
    name: rpi_sued
    scan_interval: 15
    count: 2
  - platform: ping
    host: !secret devolo_bridge_ip
    name: devolo_bridge
    scan_interval: 60
    count: 2
  - platform: ping
    host: !secret devolo_stk_ip
    name: devolo_steuerkasten
    scan_interval: 60
    count: 3
  - platform: ping
    host: !secret devolo_keller_ip
    name: devolo_keller
    scan_interval: 60
    count: 4
###############################################################################
#                               Automations
###############################################################################
automation:
  #----------------------------------------------------------------------------------
  # Speedtest: Device and entities go unavailable sometimes. Restart service if this happens.
  # see: https://community.home-assistant.io/t/speedtest-integration-no-longer-loading/297167/55
  - id: reload_speedtest
    alias: Re-Load Speedtest integration
    description: 'Perform a manual speed test when sensors goes unavailable'
    trigger:
      - platform: state
        entity_id: sensor.speedtest_download
        to: unavailable
        for: 
          minutes: 15
    condition: []
    action:
#      - service: speedtestdotnet.speedtest
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.speedtest_download
    mode: single