###############################################################################
#   @author       : Max Reigl
#   @changed      : 16.10.2024
#   @created      : 08.11.2019
#   @package      : network
#   @description  : various sensors for network devices, services and performance
#   @links        : 
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: "network"
  # sensors
    # system monitor
    sensor.memory_free:
      <<: *common
    sensor.disk_use_percent:
      <<: *common
    sensor.processor_use:
      <<: *common
    sensor.network_in_eth0:
      <<: *common
    sensor.network_out_eth0:
      <<: *common
    sensor.last_boot:
      <<: *common
    # HA
    sensor.historydb_size:
      <<: *common
    sensor.current_version:
      <<: *common
    sensor.latest_version:
      <<: *common
    # Speedtest.net Sensors 
    sensor.speedtest_ping:
      <<: *common
      friendly_name: Ping
    sensor.speedtest_upload:
      <<: *common
      friendly_name: Upload Speed
      icon: mdi:cloud-upload
    sensor.speedtest_download:
      <<: *common
      friendly_name: Download Speed
      icon: mdi:cloud-download
    # Raspberries
    sensor.raspi1_cpu_usage:
      <<: *common
      icon: mdi:cpu-64-bit
    sensor.raspi2_cpu_usage:
      <<: *common
      icon: mdi:cpu-64-bit
    binary_sensor.rpi_ost:
      <<: *common
    binary_sensor.rpi_west:
      <<: *common
    binary_sensor.rpi_sued:
      <<: *common
    binary_sensor.devolo_bridge:
      <<: *common
    binary_sensor.devolo_steuerkasten:
      <<: *common
    binary_sensor.devolo_keller:
      <<: *common
    # other devices
    binary_sensor.smarttv:
      <<: *common
      icon: mdi:television  #television-classic-off
    binary_sensor.roborock:
      <<: *common
      icon: mdi:robot-vacuum
    binary_sensor.radiobad:
      <<: *common
      icon: mdi:radio
#    binary_sensor.router:
#      <<: *common
#      icon: mdi:router-network

################################################
##   Platforms
################################################
#sensor:
  # raspi-Sensors: 
    # werden automatisch erzeugt (MQTT)
  # monitor Home Assistant system state
  # - platform: systemmonitor
  #   resources:
  #   - type: disk_use_percent
  #     arg: /
  #   - type: memory_free
  #   - type: processor_use
  #   - type: network_in
  #     arg: eth0
  #   - type: network_out
  #     arg: eth0
  #   - type: last_boot

###############################################################################
#                               Automations
###############################################################################
automation:
  #----------------------------------------------------------------------------------
  # Speedtest: Device and entities go unavailable sometimes. Restart service if this happens.
  # see: https://community.home-assistant.io/t/speedtest-integration-no-longer-loading/297167/55
  - id: reload_speedtest
    alias: Re-Load Speedtest integration
    description: 'Perform a manual speed test when sensors goes unavailable'
    triggers:
      - trigger: state
        entity_id: sensor.speedtest_download
        to: unavailable
        for: 
          minutes: 15
    actions:
#      - action: speedtestdotnet.speedtest
      - action: homeassistant.update_entity
        target:
          entity_id: sensor.speedtest_download
    mode: single