################################################################
##
################################################################

#homeassistant:
#  customize:
#    group.all_doors.sensor:
#      device_class: door #binary_sensor
#      sensor_class: opening

group:
  # 'group.all_doors' fasst den Status alle Türen zusammen.
  #   Ist ein Türesensor 'on'='Offen', dann wird die Gruppe 'on'.
  all_doors:
    name: alle Türen
    entities:
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_032b77ce_1_6
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_03139f7b_1_6
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_031b3225_1_6

# Definition der Gruppe von Geräten, die benachrichtigt werden sollen,
notify:
  - name: family_main_devices
    platform: group
    services:
      - service: ios_iphonemax8
  - name: max
    platform: group
    services:
      - service: ios_iphonemax8
  - name: ing
    platform: group
    services:
      - service: ios_iphoneingrid8

automation:
  - alias: Notify all - Open Doors
    trigger:
      # niemand zuhause und mindestens eine Tür offen 
      platform: template
      value_template: "{{ ( is_state('sensor.home_status', 'Away') or is_state('sensor.home_status', 'Just Left') ) 
                          and is_state('group.all_doors', 'on') }}"
      for:
        seconds: 3
    action:
      service: notify.family_main_devices
      data:
        title: "Smart Home Alerts"
        message: "Mindestens eine Balkontür ist offen."
        data:
          subtitle: "Türen offen!"
          push:
            badge: 1
            #sound: "US-EN-Daisy-Back-Door-Open.wav"
          
          
  - alias: Test Zone Notify
    trigger:
      - platform: zone
        entity_id: group.phone_max
        zone: zone.home
        event: "leave" # Event is either enter or leave
      - platform: zone
        entity_id: group.phone_max
        zone: zone.tik
        event: "enter" # Event is either enter or leave
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'group.all_doors'
          state: 'on'
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ sensor.ing_status.state not in ["home", "Just Arrived"] }}' 
    action:
      service: notify.family_main_devices
      data:
        title: "Smart Home Alerts (Zone-test)"
        message: "Mindestens eine Balkontür ist offen."
        data:
          subtitle: "Türen offen!"
          push:
            badge: 1
