###############################################################################
#   @author       : Max Reigl
#   @changed      : 16.10.2024
#   @created      : 20.12.2019
#   @package      : notification
#   @description  : Notifications and alert values 
#   @links        : 
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: "notification"
  # sensors
    sensor.count_notification_alerts:
      <<: *common
    sensor.count_hacs_updates:
      <<: *common

################################################
##   Platforms
################################################
notify:
# Definition der Gruppe von Geräten, die benachrichtigt werden sollen,
  - name: family_main_devices
    platform: group
    services:
      - service: mobile_app_iphonemax13
      - service: mobile_app_ingrid_s_iphone
  - name: max
    platform: group
    services:
      - service: mobile_app_iphonemax13
      #- service: mobile_app_ipad_max
  - name: ing
    platform: group
    services:
      - service: mobile_app_ingrid_s_iphone 
      #- service: mobile_app_iehrlichs_ipad 

# Mail Benachrichtigung
  - name: gmail_smtp
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret gmail_user
    encryption: starttls
    username: !secret gmail_user
    password: !secret gmail_app_pwd
    recipient:
      - !secret max_email
      #- !secret ing_email
    sender_name: My Home Assistant

  - name: gmx_smtp
    platform: smtp
    server: mail.gmx.net
    port: 587
    timeout: 15
    sender: !secret gmx_user
    encryption: starttls
    username: !secret gmx_user
    password: !secret gmx_pwd
    recipient:
      - !secret max_email
    sender_name: My Home Assistant


###############################################################################
##  Sensors
###############################################################################
# sensor counts all active alerts for numbering the badge
#   more alerts can be integrated!
sensor:
  - platform: template
    sensors:
      count_notification_alerts:
        friendly_name: 'count active alerts'
        value_template: >
          {{ (1 if is_state('input_boolean.open_backdoor_alert', 'on') else 0)
            + (1 if is_state('input_boolean.open_window_alert', 'on') else 0)
            + (1 if is_state('input_boolean.dwd_weather_alert', 'on') else 0) 
            + (1 if is_state('binary_sensor.vacuum_error_alert', 'on') else 0) 
            + (1 if is_state('input_boolean.bwk_sued_offline_notification', 'on') else 0) 
            + (1 if is_state('binary_sensor.powermeter_offline_notification', 'on') else 0) 
          }}
        # numeric would be like that: + (0 if is_state('sensor.dwd_current_warn_count', '0') else 1) 
        icon_template: mdi:comment-alert

      count_hacs_updates:
        friendly_name: 'count HACS updates'
        value_template: >
          {{- integration_entities('hacs')
          | select('match', '^update\.')
          | expand
          | selectattr('state','eq', 'on')
          | list 
          | count
          -}}
        icon_template: mdi:hacs
