###############################################################################
#   @author       : Max Reigl
#   @date         : 08.10.2020
#   @package      : power
#   @description  : light/power consumtion and regulation
#   @links        : 
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: 'power'
  # entities
    switch.osram_plug_01_a1bf020a_3:
      icon: mdi:power-socket-de
    light.0008da499c8dbd:
      icon: mdi:ceiling-light
    light.philips_lightstrip_ku:
      icon: mdi:led-strip-variant
    # groups, variables
    input_boolean.disable_power_automation:
      <<: *common
    input_boolean.ll_signals_doorstatus:
      <<: *common
  # automations
    automation.random_lights_during_vacation:
      <<: *common
    automation.switch_off_lights:
      <<: *common
    automation.switch_on_lights:
      <<: *common
    automation.power_down_mediarack:
      <<: *common
    automation.power_up_mediarack:
      <<: *common
    automation.switch_off_lights_from_sz:
      <<: *common
    automation.switch_on_lights_from_sz:
      <<: *common

################################################
##   Platforms
################################################
#wake_on_lan:
#
#switch:
#  - platform: wake_on_lan
#    name: raspi1_power
#    host: !secret raspi1_ost_ip
#    mac: !secret raspi1_ost_mac
#    turn_off:
#      service: shell_command.turn_off_raspi1 

scene:
  - name: Welcome
    icon: 'mdi:flower-tulip'
    entities:
      light.0008da499c8dbd:
        state: 'on'
        #brightness: 250 #-->.brightness=249
        brightness: 125 #-->.brightness=
  - name: Movies
    entities:
      light.0008da499c8dbd:
        state: 'on'
        #brightness: 125 #-->.brightness=124
        brightness: 75 #-->.brightness=30%

###############################################################################
#                               Variables
###############################################################################
input_boolean:
  disable_power_automation:
    name: Stromabschaltung deaktivieren
    icon: mdi:robot
  ll_signals_doorstatus:
    name: Türstatus wird angezeigt
    icon: mdi:traffic-light

switch:
  - platform: template
    switches: ## are needed in addition to input_booleans to get a dynamic icon
      enable_power_automation:
        friendly_name: Automatische Stromabschaltung #   
        value_template: "{% if not states('input_boolean.disable_power_automation')=='unknown' %}{{ is_state('input_boolean.disable_power_automation', 'off') }}{% endif %}"
        turn_on:
          service: homeassistant.turn_off
          data:
            entity_id: input_boolean.disable_power_automation
        turn_off:
          service: homeassistant.turn_on
          data:
            entity_id: input_boolean.disable_power_automation
        icon_template: >-
          {% if is_state('input_boolean.disable_power_automation', 'on') %}
            mdi:ghost-off 
          {% else %}
            mdi:ghost
          {% endif %}

###############################################################################
#                               Automations
###############################################################################
automation:
  #----------------------------------------------------------------------------------
  # Urlaubslicht
  # https://community.home-assistant.io/t/new-automation-not-loading-random-switching-of-lights-when-away-on-holiday/211414/14
  - id: random_lights_during_vacation
    alias: zufälliges Urlaubslicht
    trigger:
      - platform: sun
        event: sunset
      - platform: time
        at: '23:00:00'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.disable_power_automation
        state: 'off'
      - condition: state
        entity_id: sensor.home_status
        state: 'Extended Away'
    action:
      - delay:
          minutes: "{{ range(5, 25 if trigger.platform == 'sun' else 90) | random }}"
      - service: "light.turn_{{ 'on' if trigger.platform == 'sun' else 'off' }}"
        entity_id: light.0008da499c8dbd
#  or with groups like that: 
#      - service: "homeassistant.turn_{{ 'on' if trigger.platform == 'sun' else 'off' }}"
#        entity_id: group.holiday_lights
    

  #----------------------------------------------------------------------------------
  # Welcome-/Ambientelicht 
  # Einschalten von Welcome-Licht, wenn wir nach Hause kommen ODER bei Sonnenuntergang
  - id: switch_on_lights
    alias: switch on welcome light
    trigger:
      - platform: state
        entity_id: sensor.home_status
        to: 'Home'
      - platform: sun
        event: sunset
        offset: '+00:15:00' # Optional time offset. 
      - platform: state
        entity_id: input_boolean.disable_power_automation
        to: 'off'
    condition:
      # 'power_automation' aktiv UND Home status 'Home' UND Sonne untergegangen
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.disable_power_automation
        state: 'off'
      - condition: state
        entity_id: sensor.home_status
        state: 'Home'
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.welcome
          transition: 2 #[sec] langsamer Übergang
  
  # Ausschalten von Welcome-Licht und Lichtleiste, wenn wir für 10min weg sind oder nachts um 00:00
  #   und morgens beim Sonnenaufgang
  - id: switch_off_lights
    alias: switch off welcome light
    trigger: 
      - platform: state
        entity_id: sensor.home_status
        from: 'Home'
        to: 'Away'
        for:
          minutes: 2
      - platform: state
        entity_id: input_boolean.disable_power_automation
        to: 'off'
      - platform: time 
        at: '00:01:00'
      - platform: sun
        event: sunrise
      - platform: homeassistant
        event: start      
    condition:
      # 'power_automation' aktiv UND (Home status away ODER nach 0:00)
      condition: and
      conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: sensor.home_status
          state: 'Away'
        - condition: time
          after: '00:00:00'
          before: '06:00:00'
      - condition: state
        entity_id: input_boolean.disable_power_automation
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: 
          - light.0008da499c8dbd
          - light.philips_lightstrip_ku

  #----------------------------------------------------------------------------------
  # Medien-Rack
  # Ausschalten des Medien-Racks, wenn wir für 10min weg sind
  - id: power_down_mediarack
    alias: switch off media rack
    trigger: 
      - platform: state
        entity_id: sensor.home_status
        from: 'Home'
        to: 'Away'
        for:
          minutes: 10
      - platform: state
        entity_id: input_boolean.disable_power_automation
        to: 'off'
      - platform: homeassistant
        event: start
    condition:
      # 'power_automation' aktiv UND Home status 'Away'
      condition: and
      conditions:
      - condition: state
        entity_id: sensor.home_status
        state: 'Away'
      - condition: state
        entity_id: input_boolean.disable_power_automation
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.osram_plug_01_a1bf020a_3

  # Einschalten des Media Racks, wenn wir nach Hause kommen
  - id: power_up_mediarack
    alias: switch on media rack
    trigger:
      - platform: state
        entity_id: sensor.home_status
        to: 'Home'
      - platform: state
        entity_id: input_boolean.disable_power_automation
        to: 'off'
    condition:
      # 'power_automation' aktiv UND Home status 'Home'
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.disable_power_automation
        state: 'off'
      - condition: state
        entity_id: sensor.home_status
        state: 'Home'
    action:
      - service: switch.turn_on
        entity_id: switch.osram_plug_01_a1bf020a_3


  #----------------------------------------------------------------------------------
  # HmIP-BRC2 Wandtaster schaltet Lichter an/aus
  - id: switch_off_lights_from_sz
    alias: "Ambientelicht aus"
    trigger:
      platform: event
      event_type: homematic.keypress
      event_data:
        name: '0019DBE9943030'
        channel: 1
        param: PRESS_SHORT
    action:
      service: light.turn_off
      entity_id: light.0008da499c8dbd
  - alias: "alle Licher aus"
    trigger:
      platform: event
      event_type: homematic.keypress
      event_data:
        name: '0019DBE9943030'
        channel: 1
        param: PRESS_LONG
    action:
      - service: light.turn_off
        entity_id: light.0008da499c8dbd
      - service: light.turn_off
        entity_id: light.philips_lightstrip_ku
  
  - id: switch_on_lights_from_sz
    alias: "Ambientelicht an"
    trigger:
      platform: event
      event_type: homematic.keypress
      event_data:
        name: '0019DBE9943030'
        channel: 2
        param: PRESS_SHORT
    action:
      service: light.turn_on
      entity_id: light.0008da499c8dbd  
  - alias: "alle Licher an"
    trigger:
      platform: event
      event_type: homematic.keypress
      event_data:
        name: '0019DBE9943030'
        channel: 2
        param: PRESS_LONG
    action:
      - service: light.turn_on
        entity_id: light.0008da499c8dbd  
      - service: light.turn_on
        entity_id: light.philips_lightstrip_ku

#----------------------------------------------------------------------------------
# Test für shutdown network rack

###############################################################################
##  Scripts
###############################################################################
script:
  kill_raspi1:
    alias: shutdown Raspi1 (Ost)
    sequence:
    - service: shell_command.shutdown_raspi
      data_template: 
        ip_address: !secret raspi1_ost_ip
        user: !secret raspi_user

shell_command:
  shutdown_raspi: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa "{{user}}"@"{{ip_address}}" sudo shutdown now'
  #produces an error in log file but works! Maybe because ssl looses connection... 
  #log:
  #  ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa "{{user}}"@"{{ip_address}}" sudo shutdown now`, return code: 255
  #  NoneType: None