###############################################################################
#   @author       : Max Reigl
#   @date         : 14.11.2019
#   @package      : power
#   @description  : power consumtion and regulation
#   @links        : 
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: "power"
  # groups, variables
    input_boolean.disable_power_automation:
      <<: *common
  # automations
    #automation.power_down_mediarack:
    #  <<: *common
    #automation.power_up_mediarack:
    #  <<: *common
    automation.switch_off_lights:
      <<: *common
    automation.switch_on_lights:
      <<: *common

###############################################################################
#                               Variables
###############################################################################
input_boolean:
  disable_power_automation:
    name: Stromabschaltung deaktivieren
    icon: mdi:robot

    #initial: on #default: Auto aus, da Plug sonst scheinbar das ZigBee Routing stoppt.

###############################################################################
#                               Automations
###############################################################################
#alt:
#  - id: power_down_mediarack
#    alias: switch off media rack
#  - id: power_up_mediarack
#    alias: switch on media rack

automation:
  # Ausschalten von ___ wenn wir für 10min weg sind oder nachts um 00:00
  - id: switch_off_lights
    alias: switch off welcome light
    trigger: 
    - platform: state
      entity_id: sensor.home_status
      from: 'Home'
      to: 'Away'
      for:
        minutes: 10
    - platform: state
      entity_id: input_boolean.disable_power_automation
      to: 'off'
    - platform: time 
      at: '00:05:00'
    - platform: homeassistant
      event: start
    condition:
      # 'power_automation' aktiv UND (Home status away ODER nach 0:00)
      condition: and
      conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: sensor.home_status
          state: 'Away'
        - condition: time
          after: '00:00:00'
          before: '06:00:00'
      - condition: state
        entity_id: input_boolean.disable_power_automation
        state: 'off'
    action:
    - service: switch.turn_off
      entity_id: switch.osram_plug_01_a1bf020a_3

  - id: switch_on_lights
    alias: switch on welcome light
    trigger:
      - platform: state
        entity_id: sensor.home_status
        to: 'Home'
      - platform: state
        entity_id: input_boolean.disable_power_automation
        to: 'off'
      - platform: homeassistant
        event: start
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: sensor.home_status
        state: 'Home'
      - condition: state  # from sunset until sunrise
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: switch.turn_on
        entity_id: switch.osram_plug_01_a1bf020a_3
