###############################################################################
#   @author       : Max Reigl
#   @date         : 08.10.2020
#   @package      : power
#   @description  : light/power consumtion and regulation
#   @links        : 
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: 'power'
  # constants 
      # timespans for power downs
      int_minutes_away_for_power_down: &int_minutes_away_for_power_down 20
      int_minutes_home_for_power_up: &int_minutes_home_for_power_up 2
      # entity-id's
      powerswitch_rack_entityid: &powerswitch_rack_entityid switch.fritz_dect_200_netz
      powerswitch_gz_entityid: &powerswitch_gz_entityid switch.fritz_dect_200_gz
      powerswitch_tv_entityid: &powerswitch_tv_entityid switch.ikea_of_sweden_tradfri_control_outlet_switch
      powerswitch_rpi_sued_entityid: &powerswitch_rpi_sued_entityid switch.outlet_repeater_wz_018780fe_on_off
  # entities
    switch.ikea_of_sweden_tradfri_control_outlet_switch: 
      icon: mdi:audio-video #mdi:power-socket-de
    # change Tasmota sensors from energy meter to be stored long term and displayed in energy dashboard 
    sensor.tasmotawe5_we5_total_in:
      state_class: total_increasing
      unit_of_measurement: kWh
      device_class: energy
      friendly_name: Total energy consumed
    sensor.tasmotawe5_we5_total_out:
      state_class: total_increasing
      unit_of_measurement: kWh
      device_class: energy
      friendly_name: Total energy delivered
    sensor.tasmotawe5_we5_power_cur:
      state_class: measurement
      unit_of_measurement: W
      device_class: energy
      friendly_name: current power delivery

  # groups, variables
    input_boolean.disable_power_automation:
      <<: *common
    switch.enable_power_automation:
      <<: *common
  # automations
    automation.power_down_mediarack:
      <<: *common
    automation.power_up_mediarack:
      <<: *common
    automation.switch_off_network:
      <<: *common
    automation.switch_on_network:
      <<: *common
    script.kill_raspi1:
      <<: *common
    script.reboot_raspi1:
      <<: *common
    script.reboot_raspi2:
      <<: *common
        
###############################################################################
#                               Variables
###############################################################################
input_boolean:
  disable_power_automation:
    name: Stromabschaltung deaktivieren
    icon: mdi:robot

switch:
  - platform: template
    switches: ## are needed in addition to input_booleans to get a dynamic icon
      enable_power_automation:
        friendly_name: Automatische Stromabschaltung #   
        value_template: "{% if not states('input_boolean.disable_power_automation')=='unknown' %}{{ is_state('input_boolean.disable_power_automation', 'off') }}{% endif %}"
        turn_on:
          service: homeassistant.turn_off
          data:
            entity_id: input_boolean.disable_power_automation
        turn_off:
          service: homeassistant.turn_on
          data:
            entity_id: input_boolean.disable_power_automation
        icon_template: >-
          {% if is_state('input_boolean.disable_power_automation', 'on') %}
            mdi:ghost-off-outline
          {% else %}
            mdi:ghost
          {% endif %}

###############################################################################
##  Sensors
###############################################################################
# Per Tasmota WiFi-IR Leser wird der Iskra MT631 Stromzähler ausgelesen.
# mqtt:
#   sensor:
#     - name: "Energy IN"
#       state_topic: "tele/iskra_MT631_WE5/SENSOR"
#       value_template: '{{ value_json["WE5"]["Total_in"] }}'
#       unit_of_measurement: "kWh"
#       device_class: energy
#       state_class: total_increasing #measurement 
#     - name: "Energy OUT"
#       state_topic: "tele/iskra_MT631_WE5/SENSOR"
#       value_template: '{{ value_json["WE5"]["Total_out"] }}'
#       unit_of_measurement: "kWh"
#       device_class: energy
#       state_class: total_increasing #measurement 

###############################################################################
#                               Automations
###############################################################################
automation:
  #----------------------------------------------------------------------------------
  # Medien-Rack
  # Ausschalten des Medien-Racks, wenn wir für 10min weg sind
  # zusaetzlich: Repeater-Outlet EZ ausschalten (fuer RPI Sued)
  - id: power_down_mediarack
    alias: switch off media rack
    trigger: 
      - platform: state
        entity_id: sensor.home_status
        from: 'Home'
        to: 'Away'
        for:
          minutes: *int_minutes_away_for_power_down
      - platform: state
        entity_id: input_boolean.disable_power_automation
        to: 'off'
      - platform: homeassistant
        event: start
    condition:
      # 'power_automation' aktiv UND Home status 'Away'
      condition: and
      conditions:
      - condition: state
        entity_id: sensor.home_status
        state: 'Away'
      - condition: state
        entity_id: input_boolean.disable_power_automation
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id: *powerswitch_tv_entityid
      - service: script.kill_raspi3
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.rpi_sued
            to: 'off'
        timeout:
          minutes: 1
        continue_on_timeout: true  
      # switch off power outlet EZ (RPI Sued)
      - service: switch.turn_off
        entity_id: *powerswitch_rpi_sued_entityid

  # Einschalten des Media Racks, wenn wir nach Hause kommen
  # mit 2 Minuten Verzögerung, da das Netzwerk erst wieder hochgefahren sein muss.
  # zusaetzlich: Repeater-Outlet EZ ausschalten (fuer RPI Sued)
  - id: power_up_mediarack
    alias: switch on media rack
    trigger:
      - platform: state
        entity_id: sensor.home_status
        to: 'Home'
        for: 
          minutes: *int_minutes_home_for_power_up
      - platform: state
        entity_id: input_boolean.disable_power_automation
        to: 'off'
    condition:
      # 'power_automation' aktiv UND Home status 'Home'
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.disable_power_automation
        state: 'off'
      - condition: state
        entity_id: sensor.home_status
        state: 'Home'
    action:
      - service: switch.turn_on
        entity_id: *powerswitch_tv_entityid
      # switch on power outlet EZ (RPI Sued)
      - service: switch.turn_on
        entity_id: *powerswitch_rpi_sued_entityid

  #----------------------------------------------------------------------------------
#todo: Log error: 'Unable to find referenced entities'
# - service: automation.turn_off, entity_id: automation.switch_off_network
    # FritzDect1 schaltet WLAN, Unify-Switch und Raspi aus.
  - id: switch_off_network
    mode: restart
    alias: switch off network components
    trigger: 
      - platform: state
        entity_id: sensor.home_status
        from: 'Home'
        to: 'Away'
        for:
          minutes: *int_minutes_away_for_power_down
      - platform: time
        at: '00:45:00'
    condition:
      # 'power_automation' aktiv (und Saug-E nicht aktiv für Netzwerk) 
      - condition: state
        entity_id: input_boolean.disable_power_automation
        state: 'off'
      #- condition: state
      #  entity_id: vacuum.xiaomi_vacuum_cleaner
      #  state: 'docked'
    action:
      # stop switching on the network
      - service: automation.turn_off
        entity_id: automation.switch_on_network
      - service: automation.turn_on
        entity_id: automation.switch_on_network
      # power down Desk and wait a bit (because Fritz integration does not send 2 consecutive commands)
      - service: switch.turn_off
        entity_id: *powerswitch_gz_entityid
      - delay: '00:00:05'
      - choose:
        # wenn Saug-E nicht aktiv...
        - alias: "Switch of Raspi1 and network"
          conditions:
            - condition: state
              entity_id: vacuum.xiaomi_vacuum_cleaner
              state: 
                - 'docked'
                - 'unavailable'
          sequence:
            # shut down Raspi1, and wait for it being offline
            - service: script.kill_raspi1
            - wait_for_trigger:
                - platform: state
                  entity_id: binary_sensor.rpi_ost
                  to: 'off'
              timeout:
                minutes: 1
              continue_on_timeout: true  
            # power down Raspi3
            - service: script.kill_raspi3
            - wait_for_trigger:
                - platform: state
                  entity_id: binary_sensor.rpi_sued
                  to: 'off'
              timeout:
                minutes: 1
              continue_on_timeout: true  
            # switch off power outlet EZ (RPI Sued)
            - service: switch.turn_off
              entity_id: *powerswitch_rpi_sued_entityid
            # power down Unifi components 
            - service: switch.turn_off
              entity_id: *powerswitch_rack_entityid


  - id: switch_on_network
    alias: switch_on_network #switch on network components
    mode: restart
    trigger: 
      - platform: state
        entity_id: sensor.home_status
        to: 'Home'
      - platform: state
        entity_id: group.entrance_door
        to: 'on' 
      - platform: time
        at: '06:00:00'
    condition:
      - condition: and
        conditions:
          # 'power_automation' aktiv
          - condition: state
            entity_id: input_boolean.disable_power_automation
            state: 'off'
          - condition: or
            # someone is home OR the entrance door is opened
            conditions:
              - condition: state
                entity_id: sensor.home_status
                state: 'Home'
              - "{{ trigger.entity_id == 'group.entrance_door' }}"
    action:
      # stop 'switching off the network' (if running)
      - service: automation.turn_off
        entity_id: automation.switch_off_network
      - service: automation.turn_on
        entity_id: automation.switch_off_network
      # power up Unifi components and wait for them to initialize
      - service: switch.turn_on
        entity_id: *powerswitch_rack_entityid
      # meanwhile trigger arrival scan for Raspi1. monitor.sh service will be started on Raspi1 with a delay of approx. 20secs.
      - delay: '00:00:30'
      - service: mqtt.publish
        data:
          topic: 'monitor/scan/arrive' 
          payload: "{'data' : 'west'}" #this monitor publisher will NOT respond!
      - delay: '00:01:30'
      # power up Desk ...
      - service: switch.turn_on
        entity_id: *powerswitch_gz_entityid
      # ...and switch on power outlet EZ (RPI Sued)...
      - service: switch.turn_on
        entity_id: *powerswitch_rpi_sued_entityid
      # ...and wait a bit
      - delay: '00:00:30'
      # reboot Raspi1, if not online and wait for reboot and sensors
      - choose:
        - conditions: "{{ states('sensor.raspi1_lastmessage') == 'unavailable' }}"
          sequence:
            - service: script.reboot_raspi1

      - delay: '00:01:00' 
      # switch of and on power for Raspi1. Necessary after longer power off periods
      - choose:
        - conditions: "{{ states('binary_sensor.rpi_ost') != 'on'  or  states('sensor.raspi1_lastmessage') == 'unavailable' }}"
          sequence:
            - service: switch.turn_off
              entity_id: *powerswitch_rack_entityid
            - delay: '00:00:03' 
            - service: switch.turn_on
              entity_id: *powerswitch_rack_entityid
      # switch of and on power for Raspi3. Necessary after longer power off periods
      - choose:
        - conditions: "{{ states('binary_sensor.rpi_sued') != 'on'  or  states('sensor.raspi3_lastmessage') == 'unavailable' }}"
          sequence:
            - service: switch.turn_off
              entity_id: *powerswitch_rpi_sued_entityid
            - delay: '00:00:05' 
            - service: switch.turn_on
              entity_id: *powerswitch_rpi_sued_entityid

      - delay: '00:00:45' 
      # reboot Raspi3, if not online and wait for reboot and sensors
      - choose:
        - conditions: "{{ states('sensor.raspi3_lastmessage') == 'unavailable' }}"
          sequence:
            - service: script.reboot_raspi3
      # reboot Raspi3, if not online and wait for reboot and sensors
      - choose:
        - conditions: "{{ states('sensor.raspi3_lastmessage') == 'unavailable' }}"
          sequence:
            - service: script.reboot_raspi3
            

###############################################################################
##  Scripts
###############################################################################
script:
  kill_raspi1:
    alias: shutdown Raspi1 (Ost)
    sequence:
    - service: shell_command.shutdown_raspi
      data_template: 
        ip_address: !secret raspi1_ost_ip
        user: !secret raspi_user
  kill_raspi3:
    alias: shutdown Raspi3 (Süd)
    sequence:
    - service: shell_command.shutdown_raspi
      data_template: 
        ip_address: !secret raspi3_sued_ip
        user: !secret raspi_user
  reboot_raspi1:
    alias: reboot Raspi1 (Ost)
    sequence:
    - service: shell_command.reboot_raspi
      data_template: 
        ip_address: !secret raspi1_ost_ip
        user: !secret raspi_user
  reboot_raspi2:
    alias: reboot Raspi2 (West)
    sequence:
    - service: shell_command.reboot_raspi
      data_template: 
        ip_address: !secret raspi2_west_ip
        user: !secret raspi_user
  reboot_raspi3:
    alias: reboot Raspi3 (Süd)
    sequence:
    - service: shell_command.reboot_raspi
      data_template: 
        ip_address: !secret raspi3_sued_ip
        user: !secret raspi_user


shell_command:
  shutdown_raspi: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa "{{user}}"@"{{ip_address}}" sudo shutdown now'
  reboot_raspi: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa "{{user}}"@"{{ip_address}}" sudo reboot now'
  # produces an error in log file but works! Maybe because ssl looses connection... 
  # log:
  #   ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa "{{user}}"@"{{ip_address}}" sudo shutdown now`, return code: 255
  #   NoneType: None