################################################################
## Presence Detection with different states
##
## Idea: https://philhawthorne.com/making-home-assistants-presence-detection-not-so-binary/
# evtl noch einbauen: https://www.home-assistant.io/components/bayesian/
# todo: BTLE: https://community.home-assistant.io/t/monitor-reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/68505
# Group als trigger: https://community.home-assistant.io/t/automation-trigger-on-any-member-of-a-group-is-it-possible/55795
################################################################

# Bilder für unsere Personen
homeassistant:
  customize: 
    sensor.max_status:
      entity_picture: /local/max.jpg # entspricht ./config/www/*
    sensor.ing_status:
      entity_picture: /local/ing.jpg 

group:
  # 'group.family_status' wird durch eine group-card im UI angezeigt.
  family_status:
    name: Family Status
    control: hidden
    entities:
      - sensor.max_status
      - sensor.ing_status
      - input_boolean.guests
      # - sensor.n_people_home
      - sensor.home_status
  # group.phone_* dient zum zentralen Setzen des aktuell zu prüfenden Devices pro Person.
  #   Werden mehrere Geräte angegeben, dann ist Gruppe 'on'='anwesend' wenn mindestens ein Gerät 'on' ist.
  phone_max:
    name: Phone Max
    control: hidden
    entities:
      - device_tracker.iphone8_max_wifi
      # - device_tracker.iphone8_max_bt
  phone_ing:
    name: Phone Ingrid
    control: hidden
    entities:
      - device_tracker.iphone8_ing_wifi
      # - device_tracker.iphone8_ing_bt
  # group.all_phones wird für die Berechnung der Anz. Personen Zuhause benutzt.
  all_phones:
    name: all phones
    control: hidden
    entities:
      - device_tracker.iphone8_ing_wifi
      - device_tracker.iphone8_max_wifi    
      # - device_tracker.iphone8_ing_bt
      # - device_tracker.iphone8_max_bt    

# mögliche Statuswerte für Personen und den Gesamtstatus 'sensor.home_status'
input_select:
  max_status_dropdown:
    name: Max
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
#    initial: Home # ohne 'initial' wird der letzte Zustand genommen
  ing_status_dropdown:
    name: Ingrid
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
  home_status_dropdown:
    name: Home Status
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

# Manuelle Eingabe, ob Gäste in der Wohnung sind. Erhöht der Wert von 'sensor.n_people_home' um 1.
input_boolean:
  guests:
    name: Wir haben Gäste #We have guests
    icon: mdi:account-multiple
    
sensor:
  # der Status der Personen
  - platform: template
    sensors:
      max_status:
        friendly_name: 'Max'
        value_template: '{{ states.input_select.max_status_dropdown.state }}'
        entity_id:
          - input_select.max_status_dropdown
      ing_status:
        friendly_name: 'Ingrid'
        value_template: '{{ states.input_select.ing_status_dropdown.state }}'
        entity_id:
          - input_select.ing_status_dropdown
  # Anzahl der Personen zuhause
  - platform: template
    sensors:
      n_people_home:
        friendly_name: Number of People Home
        entity_id:
          - device_tracker.iphone8_max_wifi
          - device_tracker.iphone8_ing_wifi
          - input_boolean.guests
        value_template: >
          {{ states|selectattr('entity_id','in',
                      state_attr('group.all_phones','entity_id'))
                   |selectattr('state','eq','home')|list|count +
             (1 if is_state('input_boolean.guests','on') else 0) }}
  # Gesamtstatus: ist jemand zuhause
  - platform: template
    sensors:
      home_status:
        value_template: '{{ states.input_select.home_status_dropdown.state }}'
        friendly_name: 'Home Presence Status'

automation:
# STATUS-Übergänge Personen
#
#         /-----------------------------------------------[10min]------------------------------------------------\
#        |                                                                                                        |
#        |                                                               /--------[DeviceTracker: home]------\    |
#        |                                                              |                                     |   |
#        V                                                              V                                     |   |
#       Away  --[DeviceTracker: home]-->  Just Arrived  --[10min]-->  Home  --[DeviceTracker: not_home]-->  Just Left
#        |                                    A   |                                                             A
#      [24h]                                  |   |                                                             |
#        V                                    |   \---------------------------[DeviceTracker: not_home]---------´ 
#   Extended Away  ---[DeviceTracker: home]---/
#
  - alias: Mark person as just arrived
    trigger:
      - platform: state
        entity_id: group.phone_max 
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: group.phone_ing
        from: 'not_home'
        to: 'home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'group.phone_max' %}
              input_select.max_status_dropdown
            {% else %}
              input_select.ing_status_dropdown
            {% endif %}
          option: >
            {% if trigger.entity_id == 'group.phone_max' %}
              {% if states.input_select.max_status_dropdown.state == 'Just Left' %}
                Home
              {% else %}
                Just Arrived
              {% endif %}
            {% else %}
              {% if states.input_select.ing_status_dropdown.state == 'Just Left' %}
                Home
              {% else %}
                Just Arrived
              {% endif %}
            {% endif %}
  
  - alias: Mark person as just left
    trigger:
      - platform: state
        entity_id: group.phone_max #device_tracker.iphone8_max_wifi
        from: 'home'
        to: 'not_home'
      - platform: state
        entity_id: group.phone_ing #device_tracker.iphone8_ing_wifi
        from: 'home'
        to: 'not_home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'group.phone_max' %}
              input_select.max_status_dropdown
            {% else %}
              input_select.ing_status_dropdown
            {% endif %}
          option: Just Left
  
  - alias: Mark person as home #('Just Arrived' vor 10min) oder ('Just Arrived' nach 'Just Left')
    trigger:
      - platform: state
        entity_id: input_select.max_status_dropdown
        to: 'Just Arrived'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.ing_status_dropdown
        to: 'Just Arrived'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.max_status_dropdown
        from: 'Just Left'
        to: 'Just Arrived'
      - platform: state
        entity_id: input_select.ing_status_dropdown
        from: 'Just Left'
        to: 'Just Arrived'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.max_status_dropdown' %}
              input_select.max_status_dropdown
            {% else %}
              input_select.ing_status_dropdown
            {% endif %}
          option: Home
  
  - alias: Mark person as away  #('Just Left' vor 10min) 
    trigger:
      - platform: state
        entity_id: input_select.max_status_dropdown
        to: 'Just Left'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.ing_status_dropdown
        to: 'Just Left'
        for:
          minutes: 10
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.max_status_dropdown' %}
              input_select.max_status_dropdown
            {% else %}
              input_select.ing_status_dropdown
            {% endif %}
          option: Away
  
  - alias: Mark person as extended away  #('Away' für 24h) 
    trigger:
      - platform: state
        entity_id: input_select.max_status_dropdown
        to: 'Away'
        for:
          hours: 24
      - platform: state
        entity_id: input_select.ing_status_dropdown
        to: 'Away'
        for:
          hours: 24
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.max_status_dropdown' %}
              input_select.max_status_dropdown
            {% else %}
              input_select.ing_status_dropdown
            {% endif %}
          option: Extended Away


# STATUS-Übergänge Home
#
#        /-------[n_people_home <1]--------\
#        |                                  |
#        V                                  |
#       Away  ---[n_people_home >0]---->  Home
#        |                                  A
#      [24h]                                |
#        V                                  |
#   Extended Away  ---[n_people_home >0]---/
#
  - alias: Home Status - Leaving
    trigger:
      platform: numeric_state
      entity_id: sensor.n_people_home
      below: 1
    condition:
      condition: state
      entity_id: input_select.home_status_dropdown
      state: Home
    action:
      service: input_select.select_option
      entity_id: input_select.home_status_dropdown
      data:
        option: Away

  - alias: Home Status - Arriving
    trigger:
      platform: state
      entity_id: sensor.n_people_home
    condition:
      condition: template
      value_template: >
        {{ trigger.to_state.state|int > trigger.from_state.state|int }}
    action:
      service: input_select.select_option
      entity_id: input_select.home_status_dropdown
      data:
        option: Home

  - alias: Home Status - Vacation  #('Away' für 24h) 
    trigger:
      platform: state
      entity_id: input_select.home_status_dropdown
      to: 'Away'
      for:
        hours: 24
    action:
      service: input_select.select_option
      entity_id: input_select.home_status_dropdown
      data:
        option: Extended Away
