###############################################################################
#   @author       : Max Reigl
#   @date         : 25.06.2020
#   @package      : synology
#   @description  : Sensors for Synology NAS
#   @links        : https://www.home-assistant.io/integrations/synologydsm/
###############################################################################

################################################
##  Customize
################################################
homeassistant:
  customize:
  # definitions
    package.node_anchors:
      common: &common
        package: "synology"
  # sensors
    sensor.cert_expiry_timestamp_hera:
      <<: *common
    sensor.last_boot:
      <<: *common
      friendly_name: Last Boot
      device_class: timestamp
    sensor.hera_volume_1_max_disk_temp:
      <<: *common
#    sensor.hera_dsm_avg_processes_5_min:
#      <<: *common
#    sensor.hera_dsm_avg_processes_15_min:
#      <<: *common
  # automations
    automation.update_cert_expiry_on_reboot:
      <<: *common

################################################
##   Platforms
################################################
  # Synology DSM integration (YAML Config deprecated in v2021.6)
#synology_dsm:
#  host: !secret DS_local_IP
#  port: !secret DSM_port
#  ssl: true
#  username: !secret DSM_sensor_username
#  password: !secret DSM_sensor_password
#  monitored_conditions:
#    - cpu_total_load
#    - cpu_5min_load  # Leistung: avg. # of processes + length queue (not %)
#    - cpu_15min_load # Leistung: avg. # of processes + length queue
#    - memory_real_usage
#    - disk_status
#    - disk_temp
#    - volume_status
#    - volume_size_used
#    - volume_size_total
#    - volume_percentage_used
#    - volume_disk_temp_max  # val=0, does not change. not used. min_max calculated separately.
#    #- volume_disk_temp_avg # does not work.

sensor:
  # Let's Encryt Certificate
  - platform: cert_expiry
    host: !secret ssl_cert_name
    port: 443

###############################################################################
##  Sensors
###############################################################################
#  - platform: template
#    sensors:
#      # we have to define 2 new sensors, because the value has to be divided, obsolete since 2021.3
#      hera_dsm_avg_processes_5_min:
#        friendly_name: Hera DSM Process Load (avg. 5min)
#        value_template: "{{ states('sensor.hera_cpu_load_5_min')| float / 100 }}"
#        icon_template: mdi:layers
#      hera_dsm_avg_processes_15_min:
#        friendly_name: Hera DSM Process Load (avg. 15min)
#        value_template: "{{ states('sensor.hera_cpu_load_15_min')| float / 100 }}"
#        icon_template: mdi:layers
  # calc max temperature of all discs
  - platform: min_max
    name: hera_volume_1_max_disk_temp
    type: max
    entity_ids:
      - sensor.hera_drive_1_temperature
      - sensor.hera_drive_2_temperature
      - sensor.hera_drive_3_temperature

###############################################################################
##  Automations
###############################################################################
automation:
  - id: update_cert_expiry_on_reboot
    alias: update_cert_expiry_on_reboot
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: "0:00:50"
      - service: homeassistant.update_entity
        entity_id: sensor.cert_expiry_timestamp_hera